POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "content": "Username note 3",
    "important": true
}

###
POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "important": true
}