GET http://localhost:3001/api/notes/61d98795c15b71fd93c4b8c9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZDc0NWU5MGFjMTNhNmMwODUwNDA5ZiIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE2NDE2NDU5MDgsImV4cCI6MTY0MTczMjMwOH0.gntcmNLo7NVw_OF1zk9cAqiAC77p1KIZJcMSBHKQVn4